# -*- coding: utf-8 -*-
# Endovia (Object Init)
# Copyright (C) 2010-2020 Jeremy Aaron Flexer.

import Walls
import Floors
import Windows
import Doors
import Fences
import Gates
import Fridges
import Chests
import Shelves
import Crates
import Boxes
import Barrels
import Sacks
import Fountains
import Pillars
import Beds
import Desks
import Ovens
import Sinks
import Larders
import Cabinets
import Wells
import Lights
import Cages
import Furnaces
import Anvils
import Fires
import Trees
import Veins
import Geodes
import Rocks
import Bunches
import Clusters
import Bushes
import Crops
import Patches
import Seats
import Tables
import Statues
import Alters
import Fisheries
import Looms

objects = {
0: Walls.walls(),
1: Floors.floors(),
2: Windows.windows(),
3: Doors.doors(),
4: Fences.fences(),
5: Gates.gates(),
6: Fridges.fridges(),
7: Chests.chests(),
8: Shelves.shelves(),
9: Crates.crates(),
10: Boxes.boxes(),
11: Barrels.barrels(),
12: Sacks.sacks(),
13: Fountains.fountains(),
14: Pillars.pillars(),
15: Beds.beds(),
16: Desks.desks(),
17: Ovens.ovens(),
18: Sinks.sinks(),
19: Larders.larders(),
20: Cabinets.cabinets(),
21: Wells.wells(),
22: Lights.lights(),
23: Cages.cages(),
24: Furnaces.furnaces(),
25: Anvils.anvils(),
26: Fires.fires(),
27: Trees.trees(),
28: Veins.veins(),
29: Geodes.geodes(),
30: Rocks.rocks(),
31: Bunches.bunches(),
32: Clusters.clusters(),
33: Bushes.bushes(),
34: Crops.crops(),
35: Patches.patches(),
36: Seats.seats(),
37: Tables.tables(),
38: Statues.statues(),
39: Alters.alters(),
40: Fisheries.fisheries(),
41: Looms.looms()
}

# Jafinoxal.
