# -*- coding: utf-8 -*-
# Endovia (Constant)
# Copyright (C) 2010-2020 Jeremy Aaron Flexer.

CHARACTER_CATEGORIES = 2

CHARACTER_CATEGORY = 0
CHARACTER_IDCHARACTER = 1
CHARACTER_NAME = 2
CHARACTER_KIND = 3
CHARACTER_DESCRIPTION = 4
CHARACTER_SYMBOL = 5
CHARACTER_COLOR = 6
CHARACTER_CLIP = 7
CHARACTER_TRANSPARENT = 8
CHARACTER_AGGRESSIVE = 9
CHARACTER_HEALTH = 10
CHARACTER_ATTACK = 11

RODENT_COUNT = 13

PLAYERS = 2000 # Complete.
RODENTS = 2001 # Complete.

# Jafinoxal.
